//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ytl.AbittiUsb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ytl.AbittiUsb.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kirjoitettu.
        /// </summary>
        internal static string Burned {
            get {
                return ResourceManager.GetString("Burned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjoita palvelintikuiksi.
        /// </summary>
        internal static string BurnExamStick {
            get {
                return ResourceManager.GetString("BurnExamStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjoita opiskelijan tikuiksi.
        /// </summary>
        internal static string BurnStudentStick {
            get {
                return ResourceManager.GetString("BurnStudentStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string ByteSuffix {
            get {
                return ResourceManager.GetString("ByteSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} Tyhjennä tikku ensin..
        /// </summary>
        internal static string CleanDiskFirst {
            get {
                return ResourceManager.GetString("CleanDiskFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakemisto levykuville.
        /// </summary>
        internal static string DiskImageFolder {
            get {
                return ResourceManager.GetString("DiskImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selaa....
        /// </summary>
        internal static string DiskImageFolderBrowse {
            get {
                return ResourceManager.GetString("DiskImageFolderBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palauta oletushakemisto.
        /// </summary>
        internal static string DiskImageFolderReset {
            get {
                return ResourceManager.GetString("DiskImageFolderReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lataa uusin versio.
        /// </summary>
        internal static string DownloadNewVersionExam {
            get {
                return ResourceManager.GetString("DownloadNewVersionExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lataa uusin versio.
        /// </summary>
        internal static string DownloadNewVersionServer {
            get {
                return ResourceManager.GetString("DownloadNewVersionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arvioidaan jäljellä olevaa aikaa....
        /// </summary>
        internal static string EvaluateTimeLeft {
            get {
                return ResourceManager.GetString("EvaluateTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyhjennä valitut.
        /// </summary>
        internal static string FormatStick {
            get {
                return ResourceManager.GetString("FormatStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tyhjennetään....
        /// </summary>
        internal static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opiskelijan tikku.
        /// </summary>
        internal static string HeaderForDownloadExam {
            get {
                return ResourceManager.GetString("HeaderForDownloadExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palvelintikku.
        /// </summary>
        internal static string HeaderForDownloadServer {
            get {
                return ResourceManager.GetString("HeaderForDownloadServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tikku luotu {1} ({0})..
        /// </summary>
        internal static string ImageFileInfo {
            get {
                return ResourceManager.GetString("ImageFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tikku ajantasalla.
        /// </summary>
        internal static string ImageUpToDate {
            get {
                return ResourceManager.GetString("ImageUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbittiUSB tarvitsee vähintään 8 Gt levytilaa, jotta levykuvia voidaan ladata ja purkaa. Vapaana on ({0}), vapauta levytilaa..
        /// </summary>
        internal static string InsufficientDiskSpace {
            get {
                return ResourceManager.GetString("InsufficientDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbittiUSB tarvitsee toimiakseen verkkoyhteyden. Tarkista, että verkkoyhteys on olemassa ja käynnistä AbittiUSB uudelleen..
        /// </summary>
        internal static string NetworkUnavailable {
            get {
                return ResourceManager.GetString("NetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi versio latautuu.
        /// </summary>
        internal static string NewVersionLoading {
            get {
                return ResourceManager.GetString("NewVersionLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}/{1} tikkua valittu).
        /// </summary>
        internal static string NumberOfSelectedSticks {
            get {
                return ResourceManager.GetString("NumberOfSelectedSticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkista uudelleen..
        /// </summary>
        internal static string RecheckDiskSpace {
            get {
                return ResourceManager.GetString("RecheckDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse kaikki:.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse käsiteltävät tikut.
        /// </summary>
        internal static string SelectSticks {
            get {
                return ResourceManager.GetString("SelectSticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruuta.
        /// </summary>
        internal static string SettingsCancel {
            get {
                return ResourceManager.GetString("SettingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallenna asetukset.
        /// </summary>
        internal static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asetukset.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arvioitu jäljellä oleva latausaika {0}..
        /// </summary>
        internal static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sovelluksessa tapahtui odottamaton virhe. Tapahtuma on lähetetty eteenpäin, tarvittaessa ota yhteyttä Abitti-tukitiimiin..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varmennettu.
        /// </summary>
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varmenna palvelintikut.
        /// </summary>
        internal static string VerifyServerBurn {
            get {
                return ResourceManager.GetString("VerifyServerBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varmenna opiskelijoiden tikut.
        /// </summary>
        internal static string VerifyStudentBurn {
            get {
                return ResourceManager.GetString("VerifyStudentBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiedosto ladattu, tarkistetaan tiedostoa....
        /// </summary>
        internal static string VerifyZipImage {
            get {
                return ResourceManager.GetString("VerifyZipImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbittiUSB ({0}).
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiedoston tarkistus epäonnistui, lataa uudestaan..
        /// </summary>
        internal static string ZipFileVerificationFailed {
            get {
                return ResourceManager.GetString("ZipFileVerificationFailed", resourceCulture);
            }
        }
    }
}
